#!/usr/bin/env bash
# .ops-core/lib/env_materialize.sh — Env file materialization helpers.
#
# Supports materialization modes declared in project config or YAML fallback:
#   symlink        — create/update <service_path>/.env → <source_file>
#   generated_file — write ephemeral .ops.project/generated/env/<service>.env from assembled context
#
# The 'none' mode (default) requires no materialization — env_exec handles it.
#
# Requires: init.sh, logger.sh, manifest.sh, env.sh (sourced first)

set -euo pipefail
if [[ "${_OPS_CORE_ENV_MATERIALIZE_LOADED:-}" == "1" ]]; then return 0; fi
_OPS_CORE_ENV_MATERIALIZE_LOADED=1

# ============================================================================
# SYMLINK MODE
# ============================================================================

# Create or update a symlink at <service_path>/.env pointing to <source_file>.
# Idempotent — no-op when the symlink is already correct.
# Fails if a regular file (not symlink) already exists at the target location.
#
# Usage: env_materialize_symlink <service-id> <source_file_rel_to_project_root>
env_materialize_symlink() {
  local service_id="${1:?env_materialize_symlink: service id required}"
  local source_rel="${2:?env_materialize_symlink: source file required}"

  local svc_path
  svc_path="$(project_get_service_field "${service_id}" path)"
  local abs_svc="${OPS_PROJECT_ROOT}/${svc_path}"
  local abs_src="${OPS_PROJECT_ROOT}/${source_rel}"
  local link_path="${abs_svc}/.env"

  require_within_root "${abs_svc}"
  [[ -f "${abs_src}" ]] || die "env_materialize_symlink: source file not found: ${source_rel}"

  if [[ -L "${link_path}" ]]; then
    local current
    current="$(readlink -f "${link_path}" 2>/dev/null || true)"
    if [[ "${current}" == "${abs_src}" ]]; then
      debug "symlink already correct: ${link_path} → ${abs_src}"
      return 0
    fi
    ops_info "Updating symlink: ${svc_path}/.env → ${source_rel}"
    ln -sf "${abs_src}" "${link_path}"
  elif [[ -e "${link_path}" ]]; then
    die "Cannot create symlink: '${link_path}' is a regular file. Move or remove it first."
  else
    ops_info "Creating symlink: ${svc_path}/.env → ${source_rel}"
    ln -sf "${abs_src}" "${link_path}"
  fi

  ops_ok "Materialized (symlink): ${svc_path}/.env → ${source_rel}"
}

# Remove the symlink created by env_materialize_symlink.
# Safe to call even if the symlink does not exist.
#
# Usage: env_materialize_symlink_cleanup <service-id>
env_materialize_symlink_cleanup() {
  local service_id="${1:?env_materialize_symlink_cleanup: service id required}"
  local svc_path
  svc_path="$(project_get_service_field "${service_id}" path)"
  local link_path="${OPS_PROJECT_ROOT}/${svc_path}/.env"

  if [[ -L "${link_path}" ]]; then
    rm -f "${link_path}"
    debug "Removed symlink: ${link_path}"
  fi
}

# ============================================================================
# GENERATED FILE MODE
# ============================================================================

# Write an ephemeral .ops.project/generated/env/<service-id>.env from the currently assembled
# OPS_ENV_CONTEXT. Caller must have called env_assemble_context first, or
# pass --assemble to trigger it automatically.
# File is chmod 600. Returns the generated file path via stdout.
# Call env_materialize_cleanup after the command finishes.
#
# Usage: env_materialize_generated <service-id> [--assemble] [--ci-mode]
env_materialize_generated() {
  local service_id="${1:?env_materialize_generated: service id required}"
  shift
  local do_assemble=false ci_flag=""
  local arg
  for arg in "$@"; do
    case "${arg}" in
      --assemble) do_assemble=true ;;
      --ci-mode)  ci_flag="--ci-mode" ;;
    esac
  done

  [[ "${do_assemble}" == "true" ]] && env_assemble_context "${service_id}" ${ci_flag}

  local env_dir="${OPS_PROJECT_GENERATED_DIR:-${OPS_PROJECT_ROOT}/.ops.project/generated}/env"
  ensure_dir "${env_dir}"
  local out="${env_dir}/${service_id}.env"

  {
    printf '# Generated by ops env broker\n'
    printf '# Service: %s\n' "${service_id}"
    printf '# Generated at: %s\n' "$(ops_timestamp)"
    printf '# DO NOT COMMIT — this file is ephemeral\n'
    local k
    while IFS= read -r k; do
      [[ -z "${k}" ]] && continue
      printf '%s=%s\n' "${k}" "${OPS_ENV_CONTEXT[${k}]}"
    done < <(printf '%s\n' "${!OPS_ENV_CONTEXT[@]}" | sort)
  } > "${out}"

  chmod 600 "${out}"
  debug "env_materialize_generated: wrote ${out}"
  printf '%s' "${out}"
}

# Remove the ephemeral generated env file for a service.
# Safe to call even if the file does not exist.
#
# Usage: env_materialize_cleanup <service-id>
env_materialize_cleanup() {
  local service_id="${1:?env_materialize_cleanup: service id required}"
  local env_dir="${OPS_PROJECT_GENERATED_DIR:-${OPS_PROJECT_ROOT}/.ops.project/generated}/env"
  local out="${env_dir}/${service_id}.env"
  if [[ -f "${out}" ]]; then
    rm -f "${out}"
    debug "env_materialize_cleanup: removed ${out}"
  fi
}

# ============================================================================
# DISPATCH — called by execution engine (Phase 3) based on manifest field
# ============================================================================

# Dispatch materialization based on the service's env_materialization field.
# 'none' → no-op; 'symlink' → symlink; 'generated_file' → generated file.
# For generated_file, prints the output path to stdout.
#
# Usage: env_materialize_dispatch <service-id> [--ci-mode]
env_materialize_dispatch() {
  local service_id="${1:?env_materialize_dispatch: service id required}"
  shift

  local mode
  mode="$(project_get_service_field "${service_id}" env_materialization 2>/dev/null || true)"
  [[ -z "${mode}" || "${mode}" == "null" ]] && mode="none"

  case "${mode}" in
    none)
      debug "env_materialize_dispatch: mode=none for '${service_id}' — no file materialization"
      ;;
    symlink)
      local output_file
      output_file="$(project_get_service_field "${service_id}" env_output_file 2>/dev/null || true)"
      [[ -z "${output_file}" || "${output_file}" == "null" ]] && \
        die "services.${service_id}.env_output_file must be set when env_materialization=symlink"
      env_materialize_symlink "${service_id}" "${output_file}" "$@"
      ;;
    generated_file)
      env_materialize_generated "${service_id}" --assemble "$@"
      ;;
    *)
      die "services.${service_id}.env_materialization — unknown mode: '${mode}'"
      ;;
  esac
}
