#!/usr/bin/env bash
# .ops-core/commands/bootstrap.sh — One-shot .ops.yaml generator.
#
# Seeds the manifest by scanning the workspace for service directories and
# stack fingerprints. Reference files are generated later by setup.
#!/usr/bin/env bash
# .ops-core/commands/bootstrap.sh — One-shot .ops.yaml generator.
#
# Scans the workspace for service directories and stack fingerprints.
# Reference files are generated later by setup.
#
# Usage: ./ops.sh experimental bootstrap [--dry-run] [--force]

set -euo pipefail

_SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/init.sh
source "${_SELF_DIR}/../lib/init.sh"
# shellcheck source=../lib/logger.sh
source "${_SELF_DIR}/../lib/logger.sh"
# shellcheck source=../lib/detect.sh
source "${_SELF_DIR}/../lib/detect.sh"
# shellcheck source=../lib/backup.sh
source "${_SELF_DIR}/../lib/backup.sh"

DRY_RUN=false
FORCE=false

for _arg in "$@"; do
  case "${_arg}" in
    --dry-run) DRY_RUN=true ;;
    --force)   FORCE=true ;;
    --help|-h)
      cat <<'EOF'
Usage: ./ops.sh experimental bootstrap [--dry-run] [--force]

Scans the workspace and seeds .ops.yaml from detected services.

Flags:
  --dry-run    Print generated YAML; do not write .ops.yaml.
  --force      Overwrite an existing .ops.yaml (auto-backup created).
EOF
      exit 0
      ;;
    *) die "Unknown flag: ${_arg}. Use --help for usage." ;;
  esac
done

if [[ "${DRY_RUN}" == false && -f "${OPS_MANIFEST}" && "${FORCE}" == false ]]; then
  ops_error ".ops.yaml already exists at: ${OPS_MANIFEST}"
  ops_info  "Use --force to overwrite (a backup will be created), or --dry-run to preview."
  exit 1
fi

_project_name="$(basename "${OPS_PROJECT_ROOT}")"
_generated_at="$(ops_timestamp)"

_humanize_id() {
  local raw="$1"
  awk -v value="${raw}" 'BEGIN {
    n = split(value, parts, /[_-]+/)
    first = 1
    for (i = 1; i <= n; i++) {
      part = parts[i]
      if (part == "") continue
      if (!first) printf " "
      printf "%s%s", toupper(substr(part, 1, 1)), tolower(substr(part, 2))
      first = 0
    }
  }'
}

_write_service() {
  local id="$1" name="$2" stack="$3" path="$4"
  local has_runtime=true
  [[ "${id}" == "api_core" ]] && has_runtime=false

  printf '  - id: %s\n' "${id}"
  printf '    name: "%s"\n' "${name}"
  printf '    stack: %s\n' "${stack}"
  printf '    path: %s\n' "${path}"
  printf '    env_files: []\n'
  printf '    env_policy: dev_file\n'
  printf '    env_materialization: none\n'
  printf '    env_output_file: ""\n'
  printf '    actions:\n'
  printf '      start: ""\n'
  printf '      stop: ""\n'
  printf '      logs: ""\n'
  printf '      build: ""\n'
  printf '      test: ""\n'
  printf '      lint: ""\n'
  printf '    depends_on: []\n'
  printf '    healthcheck: ""\n'
  if [[ "${has_runtime}" != true ]]; then
    printf '    # note: api_core is a shared library; start/stop/logs are intentionally empty.\n'
  fi
  printf '    meta:\n'
  printf '      source: detect_scan_project\n'
  printf '      confirmed_by_user: false\n'
  printf '      generated_at: "%s"\n' "${_generated_at}"
  printf '\n'
}

_generate_manifest() {
  cat <<EOF
# .ops.yaml — ops orchestrator manifest
# Generated by:  ops experimental bootstrap
# Generated at:  ${_generated_at}
#
# Edit this file to customize service definitions.
# Validate with: ./ops.sh experimental validate

version: "1"

project:
  name: ${_project_name}
  global_env_files: []
  defaults:
    env_policy: dev_file

services:

EOF

  local found_any=false
  local id rel_path stack score
  while IFS=$'\t' read -r id rel_path stack score; do
    [[ -z "${id}" ]] && continue
    found_any=true
    _write_service "${id}" "$(_humanize_id "${id}")" "${stack}" "${rel_path}"
  done < <(detect_scan_project)

  [[ "${found_any}" == true ]] || die "No services detected. Run setup/init to create reference project metadata first."

  cat <<'EOF'
ci:
  env_policy: ci_system
  skip_local_env_files: true

overrides: {}
EOF
}

ops_section "ops experimental bootstrap"

if [[ "${DRY_RUN}" == true ]]; then
  ops_info "Dry-run mode — printing generated manifest (not writing to disk)."
  printf '\n'
  _generate_manifest
  printf '\n'
  ops_ok "Dry-run complete. Run without --dry-run to write .ops.yaml."
  exit 0
fi

if [[ -f "${OPS_MANIFEST}" ]]; then
  ops_info "Backing up existing .ops.yaml..."
  ops_backup_manifest > /dev/null
fi

_TMP_MANIFEST="${OPS_MANIFEST}.bootstrap.$$"
trap 'rm -f "${_TMP_MANIFEST}"' EXIT

ops_info "Generating manifest from detected services..."
_generate_manifest > "${_TMP_MANIFEST}"

mv "${_TMP_MANIFEST}" "${OPS_MANIFEST}"

ops_ok "Manifest written → ${OPS_MANIFEST}"
ops_info "Next: validate with './ops.sh experimental validate'"
  # CI block
